version: '3'
services:
  prism:
    image: stoplight/prism:5.8.1
    restart: always
    ports:
    - "4010:4010"
    command: mock -h 0.0.0.0 /prism/openapi.yaml
    volumes:
      - ./specification:/prism
    networks:
    - intranet

networks:
    intranet: